(function () {
  'use strict';
  var API = 'https://script.google.com/macros/s/AKfycbxUe4QyBvSiL9UJsL-nsJ5XrohDabwqhYYR9q5CTgLYiW1ZCfVy429iMlpU-lCDUSvvRg/exec';
  var SESSION = 'ygEditorSessionV1';
  var CACHE = 'ygPublicContentV1';
  var fields = ['heroEyebrow','heroTitle','heroDescription','heroTagline','programTitle','fundingTitle','coverageTitle'];
  var partners = ['Aramco Asia Singapore','Global Environment Centre','Pan Pacific Conservation Foundation (PPCF)','Aliansi Kolibri','Yayasan Penabulu'];
  var logos = {};
  function el(x){return document.getElementById(x);}
  function rid(){return 'content-'+Date.now()+'-'+Math.random().toString(36).slice(2);}
  function auth(){try{return JSON.parse(localStorage.getItem(SESSION)||'null');}catch(e){return null;}}
  function status(node,text,error){node.textContent=text||'';node.classList.toggle('error',!!error);}
  function jsonp(params){return new Promise(function(resolve,reject){var cb='__ygc'+Date.now()+Math.random().toString(36).slice(2),s=document.createElement('script'),timer=setTimeout(function(){done();reject(new Error('Waktu koneksi habis.'));},20000);function done(){clearTimeout(timer);delete window[cb];if(s.parentNode)s.remove();}window[cb]=function(data){done();resolve(data);};params.callback=cb;s.src=API+'?'+Object.keys(params).map(function(k){return encodeURIComponent(k)+'='+encodeURIComponent(params[k]);}).join('&');s.onerror=function(){done();reject(new Error('Tidak dapat menghubungi Apps Script.'));};document.head.appendChild(s);});}
  function post(values){var form=new URLSearchParams();Object.keys(values).forEach(function(k){form.append(k,values[k]);});return fetch(API,{method:'POST',mode:'no-cors',body:form});}
  async function poll(page,requestId){for(var i=0;i<20;i+=1){await new Promise(function(r){setTimeout(r,900);});var data=await jsonp({page:page,requestId:requestId});if(!data.pending)return data;}throw new Error('Waktu proses habis. Periksa deployment Apps Script.');}
  async function login(){var button=el('loginButton');button.disabled=true;status(el('loginStatus'),'Memeriksa akun...');try{var requestId=rid();await post({action:'editor-login',requestId:requestId,username:el('username').value.trim(),password:el('password').value});var data=await poll('editor-auth-result',requestId);if(!data.ok)throw new Error(data.error||'Login gagal.');if(data.role!=='admin')throw new Error('Hanya administrator yang dapat mengubah konten publik.');localStorage.setItem(SESSION,JSON.stringify(data));show();}catch(e){status(el('loginStatus'),e.message,true);}button.disabled=false;}
  function key(name){return name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
  function render(content){var wrap=el('logoFields');wrap.innerHTML='';partners.forEach(function(name){var k=key(name),row=document.createElement('div'),url=content.partnerLogos&&content.partnerLogos[k];row.className='logo-field';row.innerHTML='<div><strong>'+name+'</strong><small>PNG, JPG, atau WebP; maksimum 3 MB.</small></div>'+(url?'<img src="'+url.replace(/"/g,'&quot;')+'" alt="Logo">':'<span>Belum ada logo</span>')+'<input type="file" accept="image/png,image/jpeg,image/webp">';row.querySelector('input').addEventListener('change',function(event){var file=event.target.files[0];if(!file)return;if(file.size>3*1024*1024){event.target.value='';status(el('saveStatus'),'Ukuran logo maksimum 3 MB.',true);return;}var reader=new FileReader();reader.onload=function(){logos[k]=reader.result;status(el('saveStatus'),'Logo baru siap disimpan.');};reader.readAsDataURL(file);});wrap.appendChild(row);});}
  async function load(){var content={};try{content=await jsonp({page:'public-content'});}catch(e){try{content=JSON.parse(localStorage.getItem(CACHE)||'{}');}catch(ignore){content={};}}fields.forEach(function(name){var input=document.querySelector('[data-field="'+name+'"]');if(input&&content[name]!=null)input.value=content[name];});render(content);}
  async function save(){var session=auth();if(!session||!session.sessionToken){logout();return;}var payload={partnerLogos:logos};fields.forEach(function(name){payload[name]=document.querySelector('[data-field="'+name+'"]').value.trim();});el('saveButton').disabled=true;status(el('saveStatus'),'Menyimpan konten...');try{var requestId=rid();await post({action:'content-save',requestId:requestId,sessionToken:session.sessionToken,payload:JSON.stringify(payload)});var data=await poll('content-save-result',requestId);if(!data.ok)throw new Error(data.error||'Penyimpanan gagal.');localStorage.setItem(CACHE,JSON.stringify(data.content));logos={};render(data.content);status(el('saveStatus'),'Konten publik berhasil disimpan. Muat ulang beranda untuk melihat perubahan.');}catch(e){status(el('saveStatus'),e.message,true);}el('saveButton').disabled=false;}
  function show(){el('loginPanel').hidden=true;el('editorPanel').hidden=false;load();}
  function logout(){localStorage.removeItem(SESSION);location.reload();}
  document.addEventListener('DOMContentLoaded',function(){el('loginButton').addEventListener('click',login);el('password').addEventListener('keydown',function(e){if(e.key==='Enter')login();});el('saveButton').addEventListener('click',save);el('logoutButton').addEventListener('click',logout);var session=auth();if(session&&session.sessionToken&&session.role==='admin'&&(!session.expiresAt||Number(session.expiresAt)>Date.now()))show();});
}());
