(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DEFAULT_CENTER=[0.72,101.45];
const API_BASE='https://yg-webgis-public-data.yg-webgis-public-data-worker.workers.dev';
const baseLayer=()=>L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap'});
let missionMap,resultMap,drawnItems,gridLayer,currentRasterLayer,currentJob=null,pollTimer=null;

function session(){try{return JSON.parse(localStorage.getItem('ygEditorSessionV1')||sessionStorage.getItem('ygEditorSessionV1')||'null')}catch{return null}}
function token(){const s=session();return s&&s.token&&Number(s.expiresAt||0)>Date.now()?s.token:''}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
async function api(path,options={}){const headers=new Headers(options.headers||{});const t=token();if(t)headers.set('authorization',`Bearer ${t}`);const r=await fetch(`${API_BASE}${path}`,{...options,headers});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data;}
function activateTab(name){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===`panel-${name}`));setTimeout(()=>{missionMap?.invalidateSize();resultMap?.invalidateSize();},100)}
$$('.tab').forEach(b=>b.addEventListener('click',()=>activateTab(b.dataset.tab)));$$('[data-tab-target]').forEach(b=>b.addEventListener('click',()=>activateTab(b.dataset.tabTarget)));

function setAuthState(){const ok=!!token();$('#authStatus').textContent=ok?'Login staf aktif':'Login staf diperlukan';$('#authStatus').className=`status ${ok?'good':'warn'}`;$('#startOrthomosaic').disabled=!ok;}

function initResultMap(){resultMap=L.map('resultMap',{preferCanvas:true}).setView(DEFAULT_CENTER,8);baseLayer().addTo(resultMap)}
function initMissionMap(){missionMap=L.map('missionMap',{preferCanvas:true}).setView(DEFAULT_CENTER,10);baseLayer().addTo(missionMap);drawnItems=new L.FeatureGroup().addTo(missionMap);gridLayer=new L.FeatureGroup().addTo(missionMap);const draw=new L.Control.Draw({position:'topleft',draw:{polyline:false,rectangle:true,circle:false,circlemarker:false,marker:false,polygon:{allowIntersection:false,showArea:true}},edit:{featureGroup:drawnItems,remove:true}});missionMap.addControl(draw);missionMap.on(L.Draw.Event.CREATED,e=>{drawnItems.clearLayers();drawnItems.addLayer(e.layer);gridLayer.clearLayers();$('#missionStatus').textContent='Area siap';$('#missionStatus').className='status good'});missionMap.on(L.Draw.Event.DELETED,()=>{gridLayer.clearLayers();$('#missionStatus').textContent='Belum dibuat';$('#missionStatus').className='status neutral'})}
function polygonLatLngs(){const layers=drawnItems.getLayers();if(!layers.length)return null;const ll=layers[0].getLatLngs();return Array.isArray(ll[0])?ll[0]:ll}
function intersectionsAtY(poly,y){const xs=[];for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[j],b=poly[i];if((a.lat>y)!==(b.lat>y))xs.push(a.lng+(y-a.lat)*(b.lng-a.lng)/(b.lat-a.lat))}return xs.sort((a,b)=>a-b)}
function generateGrid(){const poly=polygonLatLngs();if(!poly){alert('Gambar polygon area survei terlebih dahulu.');return}gridLayer.clearLayers();const altitude=Number($('#altitude').value)||35,side=Number($('#sideOverlap').value)||80,footprintWidth=altitude*1.45,spacingM=Math.max(3,footprintWidth*(1-side/100)),dLat=spacingM/111320,minLat=Math.min(...poly.map(p=>p.lat)),maxLat=Math.max(...poly.map(p=>p.lat));let lineNo=0;for(let y=minLat+dLat/2;y<maxLat;y+=dLat){const xs=intersectionsAtY(poly,y);for(let k=0;k+1<xs.length;k+=2){let a=[y,xs[k]],b=[y,xs[k+1]];if(lineNo%2)[a,b]=[b,a];L.polyline([a,b],{weight:2,opacity:.8,dashArray:'6 4'}).addTo(gridLayer);lineNo++}}const mission={id:`DRN-${new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14)}`,area:$('#areaName').value.trim()||'Area survei',surveyType:$('#surveyType').value,drone:$('#droneModel').value,altitude,frontOverlap:Number($('#frontOverlap').value),sideOverlap:side,speed:Number($('#speed').value),gimbal:Number($('#gimbal').value),lines:lineNo,polygon:poly.map(p=>[p.lat,p.lng]),createdAt:new Date().toISOString()};localStorage.setItem('ygDroneLastMission',JSON.stringify(mission));$('#missionStatus').textContent=`${lineNo} jalur`;$('#missionStatus').className='status good';missionMap.fitBounds(L.latLngBounds(poly).pad(.12));renderArchive()}
$('#generateMission').addEventListener('click',generateGrid);$('#clearMission').addEventListener('click',()=>{drawnItems.clearLayers();gridLayer.clearLayers();$('#missionStatus').textContent='Belum dibuat';$('#missionStatus').className='status neutral'});

function extractDjiMetadata(buffer){const bytes=new Uint8Array(buffer),decoder=new TextDecoder('utf-8',{fatal:false}),text=decoder.decode(bytes);const pick=keys=>{for(const key of keys){for(const r of [new RegExp(`${key}=["']?(-?\\d+(?:\\.\\d+)?)`,'i'),new RegExp(`<${key}>(-?\\d+(?:\\.\\d+)?)<\\/${key}>`,'i')]){const m=text.match(r);if(m)return Number(m[1])}}return null};return{pitch:pick(['drone-dji:GimbalPitchDegree','GimbalPitchDegree']),relativeAltitude:pick(['drone-dji:RelativeAltitude','RelativeAltitude'])}}
async function inspectPhotos(files){const rows=[];let valid=0,warn=0,excluded=0;for(const file of files){let status='Valid',note='Siap untuk QC fotogrametri',cls='good';try{const meta=extractDjiMetadata(await file.slice(0,1024*1024).arrayBuffer());if(meta.pitch==null){status='Warning';note='Gimbal pitch tidak ditemukan; server akan memeriksa ulang.';cls='warn';warn++}else if(meta.pitch>-85){status='Excluded';note=`Non-nadir ${meta.pitch.toFixed(1)}°; otomatis dikeluarkan dari orthomosaic.`;cls='bad';excluded++}else if(meta.pitch>-88){status='Warning';note=`Sedikit miring ${meta.pitch.toFixed(1)}°.`;cls='warn';warn++}else{note=`Nadir ${meta.pitch.toFixed(1)}°${meta.relativeAltitude!=null?` · alt ${meta.relativeAltitude.toFixed(1)} m`:''}`;valid++}}catch{status='Excluded';note='File tidak dapat dibaca.';cls='bad';excluded++}rows.push(`<tr><td>${escapeHtml(file.name)}</td><td>${(file.size/1048576).toFixed(1)} MB</td><td><span class="status ${cls}">${status}</span></td><td>${escapeHtml(note)}</td></tr>`)}$('#qcRows').innerHTML=rows.join('')||'<tr><td colspan="4" class="empty">Belum ada foto diperiksa.</td></tr>';$('#qcSummary').hidden=false;$('#qcSummary').innerHTML=`<div><span>Valid</span><strong>${valid}</strong></div><div><span>Warning</span><strong>${warn}</strong></div><div><span>Excluded</span><strong>${excluded}</strong></div>`}
$('#photoInput').addEventListener('change',e=>inspectPhotos([...e.target.files]));

function selectedSource(){return $('input[name="processSource"]:checked')?.value||'drive'}
function syncSourceChoice(){const source=selectedSource();$$('[data-source-choice]').forEach(el=>el.classList.toggle('active',el.dataset.sourceChoice===source));$('#processPhotoInput').disabled=source!=='upload';$('#driveFolderUrl').disabled=source!=='drive'}
$$('input[name="processSource"]').forEach(r=>r.addEventListener('change',syncSourceChoice));
$('#processPhotoInput').addEventListener('change',e=>{const files=[...e.target.files];const total=files.reduce((s,f)=>s+f.size,0);$('#selectedFilesText').textContent=files.length?`${files.length} foto · ${(total/1073741824).toFixed(2)} GB`:'Belum ada foto dipilih.'});
function rememberJob(id){const ids=JSON.parse(localStorage.getItem('ygDroneJobIds')||'[]').filter(Boolean);if(!ids.includes(id))ids.unshift(id);localStorage.setItem('ygDroneJobIds',JSON.stringify(ids.slice(0,30)));localStorage.setItem('ygDroneCurrentJob',id)}
function stateLabel(status){return({uploading:'Mengunggah foto',pending:'Menunggu processor',processing:'Sedang membuat orthomosaic',ready:'Selesai',failed:'Gagal diproses'})[status]||status}
function renderJob(job){currentJob=job;$('#refreshJob').disabled=false;const ready=job.status==='ready',failed=job.status==='failed';$('#jobState').className=`job-state ${ready?'ready':failed?'failed':'working'}`;$('#jobState').innerHTML=`<strong>${escapeHtml(job.title||job.id)}</strong><span>${escapeHtml(stateLabel(job.status))}</span><small>${escapeHtml(job.id)}</small>${job.sourceType==='drive'?'<small>Sumber: Google Drive</small>':`<small>${job.files?.length||0} foto diunggah</small>`}`;if(job.validPhotos!=null||job.excludedPhotos!=null){$('#serverQcSummary').hidden=false;$('#serverQcSummary').innerHTML=`<div><span>Dipakai</span><strong>${job.validPhotos||0}</strong></div><div><span>Dikeluarkan</span><strong>${job.excludedPhotos||0}</strong></div><div><span>Status</span><strong>${ready?'Siap':'QC'}</strong></div>`}else $('#serverQcSummary').hidden=true;$('#jobActions').hidden=!ready;if(ready){stopPoll();$('#resultInfo').textContent='Orthomosaic selesai. Tekan “Tampilkan di peta”.'}else if(failed){stopPoll();$('#resultInfo').textContent=job.sourceType==='drive'?'Pemrosesan gagal. Pastikan folder Drive dapat dibaca melalui link, atau gunakan Upload Foto.':'Pemrosesan gagal. Periksa dataset dan coba kembali.'}else startPoll(job.id);renderArchive()}
async function refreshJob(id=currentJob?.id||localStorage.getItem('ygDroneCurrentJob')){if(!id||!token())return;try{const data=await api(`/api/drone/jobs/${encodeURIComponent(id)}`);renderJob(data.job)}catch(e){$('#jobState').className='job-state failed';$('#jobState').textContent=`Status tidak dapat dibaca: ${e.message}`}}
function startPoll(id){stopPoll();pollTimer=setInterval(()=>refreshJob(id),20000)}function stopPoll(){if(pollTimer){clearInterval(pollTimer);pollTimer=null}}
$('#refreshJob').addEventListener('click',()=>refreshJob());

async function createDriveJob(title,url){const data=await api('/api/drone/jobs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sourceType:'drive',title,driveUrl:url})});rememberJob(data.job.id);renderJob(data.job);return data.job}
async function createUploadJob(title,files){const data=await api('/api/drone/jobs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sourceType:'upload',title})});const job=data.job;rememberJob(job.id);renderJob(job);$('#uploadProgress').hidden=false;for(let i=0;i<files.length;i++){const f=files[i];$('#uploadProgressText').textContent=`Mengunggah ${i+1}/${files.length}: ${f.name}`;$('#uploadProgressBar').style.width=`${Math.round(i/files.length*100)}%`;await api(`/api/drone/jobs/${job.id}/files/${encodeURIComponent(f.name)}`,{method:'PUT',headers:{'content-type':f.type||'image/jpeg'},body:f})}$('#uploadProgressBar').style.width='100%';$('#uploadProgressText').textContent='Upload selesai. Menambahkan ke antrean orthomosaic…';const fin=await api(`/api/drone/jobs/${job.id}/finalize`,{method:'POST'});renderJob(fin.job);return fin.job}
$('#startOrthomosaic').addEventListener('click',async()=>{if(!token()){alert('Silakan login staf terlebih dahulu.');return}const title=$('#processTitle').value.trim()||`Survei drone ${new Date().toLocaleDateString('id-ID')}`,source=selectedSource();$('#startOrthomosaic').disabled=true;try{if(source==='drive'){const url=$('#driveFolderUrl').value.trim();if(!url)throw new Error('Tempel link folder Google Drive terlebih dahulu.');await createDriveJob(title,url)}else{const files=[...$('#processPhotoInput').files];if(files.length<3)throw new Error('Pilih minimal 3 foto JPG/JPEG.');await createUploadJob(title,files)}$('#resultInfo').textContent='Dataset masuk antrean pemrosesan. Status akan diperbarui otomatis.'}catch(e){alert(`Tidak dapat memulai: ${e.message}`)}finally{$('#startOrthomosaic').disabled=!token()}});

async function showCurrentResult(){if(!currentJob||currentJob.status!=='ready')return;const url=`${API_BASE}/api/drone/jobs/${encodeURIComponent(currentJob.id)}/cog?access=${encodeURIComponent(currentJob.accessToken)}`;$('#resultInfo').textContent='Membaca Cloud Optimized GeoTIFF…';try{if(currentRasterLayer){resultMap.removeLayer(currentRasterLayer);currentRasterLayer=null}const georaster=await parseGeoraster(url);currentRasterLayer=new GeoRasterLayer({georaster,opacity:Number($('#resultOpacity').value),resolution:256});currentRasterLayer.addTo(resultMap);resultMap.fitBounds(currentRasterLayer.getBounds());$('#resultInfo').textContent=`${currentJob.title} · ${currentJob.validPhotos||0} foto digunakan · ${currentJob.excludedPhotos||0} foto dikeluarkan. COG dibaca per bagian sesuai tampilan peta.`}catch(e){$('#resultInfo').textContent=`Orthomosaic tersedia, tetapi viewer belum dapat membacanya: ${e.message}`}}
$('#showResult').addEventListener('click',showCurrentResult);$('#resultOpacity').addEventListener('input',e=>currentRasterLayer?.setOpacity(Number(e.target.value)));

async function renderArchive(){const box=$('#missionArchive'),ids=JSON.parse(localStorage.getItem('ygDroneJobIds')||'[]');const mission=JSON.parse(localStorage.getItem('ygDroneLastMission')||'null');const parts=[];if(mission)parts.push(`<div class="ortho-item"><h3>${escapeHtml(mission.area)}</h3><div class="ortho-meta"><span>${escapeHtml(mission.id)}</span><span>${escapeHtml(mission.drone)}</span><span>${mission.altitude} m</span><span>${mission.lines} jalur</span></div></div>`);if(token()){for(const id of ids.slice(0,10)){try{const d=await api(`/api/drone/jobs/${encodeURIComponent(id)}`),j=d.job;parts.push(`<div class="ortho-item"><h3>${escapeHtml(j.title)}</h3><div class="ortho-meta"><span>${escapeHtml(stateLabel(j.status))}</span><span>${escapeHtml(j.id)}</span>${j.validPhotos!=null?`<span>${j.validPhotos} foto dipakai</span>`:''}</div><div class="actions"><button data-open-job="${escapeHtml(j.id)}">Buka</button></div></div>`)}catch{}}}box.classList.toggle('empty',!parts.length);box.innerHTML=parts.join('')||'Belum ada arsip.';$$('[data-open-job]').forEach(b=>b.addEventListener('click',async()=>{localStorage.setItem('ygDroneCurrentJob',b.dataset.openJob);activateTab('process');await refreshJob(b.dataset.openJob)}))}
$('#refreshArchive').addEventListener('click',renderArchive);

setAuthState();syncSourceChoice();initResultMap();initMissionMap();renderArchive();const saved=localStorage.getItem('ygDroneCurrentJob');if(saved&&token())refreshJob(saved);
})();
