(function(){
  'use strict';
  var indonesiaBounds=L.latLngBounds([[-11.2,94.5],[6.2,141.5]]);
  var map=L.map('fire-map',{preferCanvas:true,minZoom:3}).fitBounds(indonesiaBounds,{padding:[8,8]});
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap'}).addTo(map);
  map.createPane('satellitePane');map.getPane('satellitePane').style.zIndex=205;
  map.createPane('smokePane');map.getPane('smokePane').style.zIndex=360;
  map.createPane('hotspotPane');map.getPane('hotspotPane').style.zIndex=420;
  map.createPane('infrastructurePane');map.getPane('infrastructurePane').style.zIndex=650;

  function gibs(id,matrix,options){
    return L.tileLayer('https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/'+id+'/default/default/'+matrix+'/{z}/{y}/{x}.png',Object.assign({maxNativeZoom:Number(matrix.match(/\d+$/)[0]),maxZoom:18,noWrap:true,attribution:'NASA GIBS'},options||{}));
  }
  var dateInput=document.getElementById('observation-date');
  function jakartaDate(){
    var parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());
    var values={};parts.forEach(function(p){values[p.type]=p.value});return values.year+'-'+values.month+'-'+values.day
  }
  var currentDate=jakartaDate(),observationDate=currentDate;dateInput.value=observationDate;dateInput.max=currentDate;
  var readingGuide=document.querySelector('.fw-disclaimer p');if(readingGuide)readingGuide.textContent='Warna menunjukkan dukungan ensemble yang dihaluskan dengan kernel Gaussian 30 km dan dikalikan keandalan bukti sumber. Keandalan hanya memakai jumlah deteksi, lintasan waktu, dan satelit independen; bukan status api aktif. Angin diinterpolasi pada 925, 850, atau 700 hPa berdasarkan aturan PBL dan gerak vertikal.';
  var satelliteLayer=L.tileLayer.wms('https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi',{layers:'MODIS_Terra_CorrectedReflectance_TrueColor',format:'image/jpeg',transparent:false,pane:'satellitePane',opacity:.72,time:observationDate,attribution:'NASA GIBS / MODIS Terra'});
  var groups={
    hotspots:L.layerGroup().addTo(map),satellite:L.layerGroup([satelliteLayer]),smoke:L.layerGroup(),
    villages:L.layerGroup().addTo(map),rain:L.layerGroup(),wind:L.layerGroup().addTo(map),
    fdrs:L.layerGroup().addTo(map),canals:L.layerGroup().addTo(map)
  };
  var villageGeo=null,analytics=null,hotspotGeo=null,ygBounds=null,period=1,rainLayer=null,mapDateBadge=null,hotspotStatusText='Memuat…',validationStatus=null,weatherReadings=[],weatherReady=false,aerosolReadings=[],aerosolReady=false,aerosolTime='',transportReadings=[],transportReady=false,transportTime='',transportCoverageStart=0,transportCoverageEnd=0,transportProvenance=null,ensembleReadings=[],ensembleReady=false,ensembleTime='',ensembleStatus='',ensembleCoverageStart=0,ensembleCoverageEnd=0,ensembleProvenance=null,lastSmokeField=null,smokeEntryLayers=[];
  var weatherSites=[['Aceh',5.55,95.32],['Riau',1.45,102.1],['Sumatera Selatan',-3.0,104.8],['Jakarta',-6.2,106.8],['Kalimantan Barat',-.1,109.3],['Kalimantan Tengah',-2.2,113.9],['Kalimantan Timur',.5,117.1],['Sulawesi',-2.0,121.0],['Bali',-8.4,115.2],['Maluku',-3.2,129.0],['Papua Selatan',-7.5,139.5],['Papua Utara',-2.5,140.7]];
  var hotspotModelReady=false,hotspotLatestObservation=null;
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function nameOf(p){return p.Desa||p.WADMKD||p.Nama_Desa||p.NAMOBJ||'Desa intervensi'}
  function pointTime(f){var p=f.properties||{},t=String(p.acq_time||'0000').padStart(4,'0');return new Date(p.acq_date+'T'+t.slice(0,2)+':'+t.slice(2,4)+':00Z')}
  function periodLabel(){return period===1?(observationDate===currentDate?'deteksi satelit 24 jam bergulir':'deteksi satelit 24 jam sampai akhir tanggal'):period===7?(smokeEnglish()?'7-day detection window':'jendela deteksi 7 hari'):period+' hari'}
  function periodEnd(){return observationDate===currentDate?new Date():new Date(observationDate+'T23:59:59+07:00')}
  function filteredHotspots(){var end=periodEnd(),items=(hotspotGeo&&hotspotGeo.features||[]).filter(function(f){var t=pointTime(f);return !isNaN(t)&&t<=end}),days=Number(period);var cutoff=end.getTime()-days*86400000;return items.filter(function(f){return pointTime(f).getTime()>cutoff})}
  function pointInRing(p,r){var inside=false,x=p[0],y=p[1];for(var i=0,j=r.length-1;i<r.length;j=i++){var xi=r[i][0],yi=r[i][1],xj=r[j][0],yj=r[j][1];if((yi>y)!==(yj>y)&&x<((xj-xi)*(y-yi))/((yj-yi)||1e-12)+xi)inside=!inside}return inside}
  function pointInGeometry(p,g){var polygons=!g?[]:g.type==='Polygon'?[g.coordinates]:g.type==='MultiPolygon'?g.coordinates:[];return polygons.some(function(r){return r.length&&pointInRing(p,r[0])&&!r.slice(1).some(function(h){return pointInRing(p,h)})})}
  function risk(c){return c>5?'high':c>2?'medium':c>0?'low':'zero'}
  function color(c){return {zero:'#72bd86',low:'#f2ca52',medium:'#ef8f27',high:'#d6402b'}[risk(c)]}
  function renderVillages(){
    groups.villages.clearLayers();if(!villageGeo||!hotspotGeo)return;var points=filteredHotspots();
    var alerts=[],total=0;
    var layer=L.geoJSON(villageGeo,{style:function(f){var c=points.filter(function(x){return pointInGeometry(x.geometry.coordinates,f.geometry)}).length;return {color:'#31584b',weight:1,fillColor:color(c),fillOpacity:.48}},onEachFeature:function(f,l){var p=f.properties||{},c=points.filter(function(x){return pointInGeometry(x.geometry.coordinates,f.geometry)}).length;total+=c;if(c)alerts.push({name:nameOf(p),count:c,layer:l,risk:risk(c)});l.bindPopup('<strong>'+esc(nameOf(p))+'</strong><br>'+c+' hotspot · '+periodLabel()+'<br><small>NASA FIRMS/VIIRS · confidence tinggi</small>')}}).addTo(groups.villages);
    ygBounds=layer.getBounds();document.getElementById('kpi-hotspots').textContent=total;document.getElementById('kpi-alerts').textContent=alerts.length;renderAlerts(alerts)
  }
  function renderHotspots(){groups.hotspots.clearLayers();var items=filteredHotspots();items.forEach(function(f){var p=f.properties||{},t=pointTime(f),c=f.geometry.coordinates,when=isNaN(t)?'Waktu tidak tersedia':t.toLocaleString('id-ID',{timeZone:'Asia/Jakarta',dateStyle:'medium',timeStyle:'short'})+' WIB',html='<strong>Deteksi hotspot confidence tinggi</strong><br>'+when+'<br>Satelit: '+esc(p.satellite||'—')+'<br>Koordinat: '+Number(c[1]).toFixed(5)+', '+Number(c[0]).toFixed(5);if(p.brightness!=null)html+='<br>Suhu kecerahan: '+Number(p.brightness).toFixed(1)+' K';if(p.frp!=null)html+='<br>FRP: '+Number(p.frp).toFixed(1)+' MW';html+='<br><small>NASA FIRMS · status api masih menyala atau sudah padam tidak diketahui</small>';L.circleMarker([c[1],c[0]],{pane:'hotspotPane',radius:6,color:'#7f1d1d',weight:1,fillColor:'#ef2b2d',fillOpacity:.9}).bindPopup(html).addTo(groups.hotspots)});var partial=hotspotGeo&&hotspotGeo.sourceStatus==='partial'?' · PERINGATAN: sumber parsial':'';document.getElementById('period-note').textContent=items.length+' titik daratan high confidence · '+periodLabel()+partial+' · bukan status api saat ini'}
  function refreshHotspots(){renderHotspots();renderVillages()}
  function renderAlerts(items){
    items.sort(function(a,b){return b.count-a.count});var box=document.getElementById('alert-list');document.getElementById('alert-count').textContent=items.length;
    if(!items.length){box.innerHTML='<p class="empty">Tidak ada hotspot tercatat pada periode ini di desa intervensi.</p>';return}
    box.innerHTML=items.map(function(x,i){return '<article class="fw-alert-card '+x.risk+'"><button type="button" data-alert="'+i+'"><strong>'+esc(x.name)+'</strong><span>'+x.count+' hotspot · klik untuk melihat peta</span></button></article>'}).join('');
    box.querySelectorAll('[data-alert]').forEach(function(b){b.onclick=function(){var x=items[Number(b.dataset.alert)];map.fitBounds(x.layer.getBounds(),{maxZoom:13});x.layer.openPopup()}})
  }
  function pointLayer(url,group,kind,label){return fetch(url).then(function(r){if(!r.ok)throw Error(label);return r.json()}).then(function(g){var letter=kind==='fdrs'?'F':'S';L.geoJSON(g,{pane:'infrastructurePane',pointToLayer:function(f,ll){return L.marker(ll,{pane:'infrastructurePane',riseOnHover:true,zIndexOffset:1000,icon:L.divIcon({className:'fw-infrastructure-icon',html:'<div class="fw-point '+kind+'" role="img" aria-label="'+esc(label)+'">'+letter+'</div>',iconSize:[24,24],iconAnchor:[12,12],popupAnchor:[0,-13]})})},onEachFeature:function(f,l){var p=f.properties||{},c=f.geometry&&f.geometry.coordinates||[];l.bindPopup('<strong>'+esc(p.Nama_Objek||label)+'</strong><br>'+esc(p.Desa||'')+' · '+esc(p.Tahun||'')+(c.length>1?'<br><small>Koordinat: '+Number(c[1]).toFixed(6)+', '+Number(c[0]).toFixed(6)+'</small>':''))}}).addTo(group);return (g.features||[]).length})}
  function distanceKm(a,b){var dy=(a[0]-b[0])*111,dx=(a[1]-b[1])*111*Math.cos((a[0]+b[0])*Math.PI/360);return Math.sqrt(dx*dx+dy*dy)}
  function nearestWeather(lat,lon){return weatherReadings.reduce(function(best,row){var d=distanceKm([lat,lon],[row.lat,row.lon]);return !best||d<best.distance?Object.assign({distance:d},row):best},null)}
  function nearestAerosol(lat,lon){return aerosolReadings.reduce(function(best,row){var d=distanceKm([lat,lon],[row.lat,row.lon]);return !best||d<best.distance?Object.assign({distance:d},row):best},null)}
  function destination(lat,lon,bearing,km){var r=6371,br=bearing*Math.PI/180,p1=lat*Math.PI/180,l1=lon*Math.PI/180,d=km/r,p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(br)),l2=l1+Math.atan2(Math.sin(br)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return [p2*180/Math.PI,l2*180/Math.PI]}
  function smokeClass(score){return score>75?'very-high':score>50?'high':score>25?'watch':'low'}
  function smokeEnglish(){return !!(window.YG_I18N&&window.YG_I18N.language==='en')}
  function smokeLabel(){return smokeEnglish()?'Relative support':'Dukungan relatif'}
  function smokeColor(){return '#167c80'}
  function smokeHotspots(){var end=periodEnd(),hours=24,cutoff=end.getTime()-hours*3600000;return (hotspotGeo&&hotspotGeo.features||[]).filter(function(f){var t=pointTime(f);return !isNaN(t)&&t<=end&&t.getTime()>cutoff})}
  function repeatedSourceGroups(){var end=periodEnd(),cutoff=end.getTime()-7*86400000,features=(hotspotGeo&&hotspotGeo.features||[]).filter(function(f){var t=pointTime(f);return !isNaN(t)&&t<=end&&t.getTime()>cutoff});return window.YG_SMOKE_TRANSPORT?window.YG_SMOKE_TRANSPORT.clusterRecurringSources(features,{spatialKm:2,minDays:2}):[]}
  function renderRepeatedSources(summary,en){var sources=repeatedSourceGroups();if(!sources.length){summary.className='fw-smoke-summary';summary.innerHTML=en?'<strong>Recurring thermal anomalies · 7 days</strong><p>No location has high-confidence detections on two different dates within 2 km.</p>':'<strong>Anomali panas berulang · 7 hari</strong><p>Tidak ada lokasi dengan deteksi confidence tinggi pada dua tanggal berbeda dalam jarak 2 km.</p>';return}var zones=sources.map(function(s){var zone=turf.buffer(turf.point([s.lon,s.lat]),s.radiusKm,{units:'kilometers'}),first=new Date(s.firstTime).toLocaleDateString(en?'en-GB':'id-ID',{timeZone:'Asia/Jakarta'}),last=new Date(s.lastTime).toLocaleDateString(en?'en-GB':'id-ID',{timeZone:'Asia/Jakarta'}),html=en?'<strong>Recurring thermal anomaly · 7 days</strong><br>'+s.dayCount+' dates · '+s.count+' detections · '+s.satelliteCount+' satellite(s)<br>'+first+' – '+last+'<br>Display radius: '+s.radiusKm.toFixed(1)+' km<br><small>Not a burned-area or smoke-plume boundary.</small>':'<strong>Anomali panas berulang · 7 hari</strong><br>'+s.dayCount+' tanggal · '+s.count+' deteksi · '+s.satelliteCount+' satelit<br>'+first+' – '+last+'<br>Radius tampilan: '+s.radiusKm.toFixed(1)+' km<br><small>Bukan batas area terbakar atau plume asap.</small>';L.geoJSON(zone,{pane:'smokePane',style:{color:'#a86116',weight:2,dashArray:'6 4',fillColor:'#f2ca52',fillOpacity:.2}}).bindPopup(html).addTo(groups.smoke);return zone});summary.className='fw-smoke-summary high';summary.innerHTML=en?'<strong>Recurring thermal anomalies · 7 days</strong><p>'+sources.length+' spatial clusters were detected on at least two dates within a 2 km linkage distance. Buffers are limited to 1.5–5 km and are not burned-area estimates.</p>':'<strong>Anomali panas berulang · 7 hari</strong><p>'+sources.length+' kelompok spasial terdeteksi pada sedikitnya dua tanggal dengan jarak penghubung 2 km. Buffer dibatasi 1,5–5 km dan bukan perkiraan luas terbakar.</p>'}
  function updateSmokeProductLabel(){var en=smokeEnglish(),title=document.getElementById('smoke-product-title'),note=document.getElementById('smoke-product-note');if(period===7){title.textContent=en?'Recurring Thermal Anomalies':'Anomali Panas Berulang';note.textContent=en?'At least 2 days within 7 days':'Minimal 2 hari dalam 7 hari'}else if(period===30){title.textContent=en?'Corridor Disabled':'Koridor Dinonaktifkan';note.textContent=en?'Historical markers only':'Hanya marker historis'}else{title.textContent=en?'GEFS Transport Corridors':'Koridor Transport GEFS';note.textContent=en?'Trajectory support · not a smoke polygon':'Dukungan lintasan · bukan polygon asap'}}
  function aerosolPoints(aod){return aod>=.5?25:aod>=.3?Math.round(15+(aod-.3)*50):aod>=.1?Math.round(4+(aod-.1)*55):Math.round(Math.max(0,aod)*40)}
  function timeSample(row,values,timeMs){if(!row.times.length)return 0;var after=row.times.findIndex(function(t){return t>=timeMs});if(after<0)after=row.times.length-1;var before=Math.max(0,after-1),span=row.times[after]-row.times[before],fraction=span?Math.max(0,Math.min(1,(timeMs-row.times[before])/span)):0,a=Number(values[before]),b=Number(values[after]);if(!isFinite(a))a=isFinite(b)?b:0;if(!isFinite(b))b=a;return a+(b-a)*fraction}
  function timeWind(row,wind,timeMs){if(!row.times.length)return {u:0,v:0};var after=row.times.findIndex(function(t){return t>=timeMs});if(after<0)after=row.times.length-1;var before=Math.max(0,after-1),span=row.times[after]-row.times[before],fraction=span?Math.max(0,Math.min(1,(timeMs-row.times[before])/span)):0;function vector(index){var speed=Number(wind.speeds[index])||0,direction=(Number(wind.directions[index])||0)*Math.PI/180;return {u:Math.sin(direction)*speed,v:Math.cos(direction)*speed}}var a=vector(before),b=vector(after);return {u:a.u+(b.u-a.u)*fraction,v:a.v+(b.v-a.v)*fraction}}
  function spatialRows(rows,lat,lon){return rows.map(function(row){return {row:row,distance:Math.max(.01,distanceKm([lat,lon],[row.lat,row.lon]))}}).sort(function(a,b){return a.distance-b.distance}).slice(0,4)}
  function blendWind(samples,level,timeMs){var sum=0,u=0,v=0;samples.forEach(function(item){var wind=item.row.levels[level]||item.row.levels[925],vector=timeWind(item.row,wind,timeMs),weight=1/(item.distance*item.distance);sum+=weight;u+=vector.u*weight;v+=vector.v*weight});if(!sum)return null;u/=sum;v/=sum;return {speed:Math.sqrt(u*u+v*v),direction:(Math.atan2(u,v)*180/Math.PI+360)%360}}
  function nearestTransport(lat,lon,timeMs){var samples=spatialRows(transportReadings,lat,lon);if(!samples.length)return null;var weighted=function(field){var sum=0,value=0;samples.forEach(function(item){var weight=1/(item.distance*item.distance);sum+=weight;value+=timeSample(item.row,item.row[field],timeMs)*weight});return sum?value/sum:0},pbl=weighted('pbl'),vertical=weighted('vertical'),level=pbl>=2800&&Math.abs(vertical)>=.05?700:pbl>=1400?850:925,wind=blendWind(samples,level,timeMs);return wind?{speed:wind.speed,direction:wind.direction,rain:weighted('rain'),vertical:vertical,pbl:pbl,level:level,time:timeMs}:null}
  function fireComplexes(items){var buckets={};items.forEach(function(feature){var c=feature.geometry.coordinates,p=feature.properties||{},key=Math.round(c[1]*4)+'|'+Math.round(c[0]*4),time=pointTime(feature).getTime();if(!buckets[key])buckets[key]={lat:0,lon:0,count:0,frp:0,time:0,satellites:{},passes:{},types:{},landCoverClass:null,landCoverScreened:false,persistentCandidate:false};var b=buckets[key],satellite=String(p.satellite||'unknown'),type=String(p.type==null?'':p.type).trim();b.lat+=c[1];b.lon+=c[0];b.count++;b.frp+=Math.max(0,Number(p.frp)||0);b.time=Math.max(b.time,time);b.satellites[satellite]=true;if(type)b.types[type]=true;if(p.land_cover_source)b.landCoverScreened=true;if(p.land_cover_class!=null)b.landCoverClass=Number(p.land_cover_class);b.persistentCandidate=b.persistentCandidate||p.persistent_thermal_candidate===true;if(isFinite(time))b.passes[Math.round(time/3600000)]=true});return Object.keys(buckets).map(function(key){var b=buckets[key];b.lat/=b.count;b.lon/=b.count;b.satelliteCount=Object.keys(b.satellites).length;b.passCount=Object.keys(b.passes).length;var reliability=.45+(b.count>=2?.1:0)+(b.count>=4?.1:0)+(b.satelliteCount>=2?.15:0)+(b.passCount>=2?.1:0)+(b.passCount>=3?.05:0);b.reliability=Math.min(.95,reliability);b.reliabilityLabel=b.reliability>=.8?'kuat':b.reliability>=.6?'sedang':'terbatas';b.screening=window.YG_SMOKE_TRANSPORT?window.YG_SMOKE_TRANSPORT.screenSourceComplex(b):{eligible:false,status:'withheld',reasons:['screening module unavailable']};return b})}
  function nearestEnsembleMember(lat,lon,timeMs,memberIndex,level){if(timeMs<ensembleCoverageStart||timeMs>ensembleCoverageEnd)return null;var samples=spatialRows(ensembleReadings,lat,lon).filter(function(item){return item.row.members[memberIndex]});if(!samples.length)return null;var sum=0,u=0,v=0;samples.forEach(function(item){var member=item.row.members[memberIndex],wind=member.levels[level]||member.levels[925],vector=timeWind(item.row,wind,timeMs),weight=1/(item.distance*item.distance);sum+=weight;u+=vector.u*weight;v+=vector.v*weight});if(!sum)return null;u/=sum;v/=sum;return {speed:Math.sqrt(u*u+v*v),direction:(Math.atan2(u,v)*180/Math.PI+360)%360,level:level}}
  function transportSurvivalStep(weather){
    if(!weather||weather.fallback)return 1;
    var hourlyAging=Math.pow(.5,1/18),rain=Math.max(0,Number(weather.rain)||0),wetRemoval=Math.exp(-.35*rain),verticalConfidence=Math.abs(Number(weather.vertical)||0)>.2?.9:1;
    return Math.max(.2,Math.min(1,hourlyAging*wetRemoval*verticalConfidence));
  }
  function smokeField(items){
    var step=.25,kernelKm=30,cells={},end=Math.min(periodEnd().getTime(),ensembleCoverageEnd||Infinity),coverageStart=ensembleCoverageStart||end-86400000,maxTravel=0,allComplexes=fireComplexes(items),screenedOut=allComplexes.filter(function(source){return !source.screening.eligible}),complexes=allComplexes.filter(function(source){return source.screening.eligible&&source.time>=coverageStart&&source.time<=end}),traces=[],memberCount=ensembleReadings.length?ensembleReadings.reduce(function(n,row){return Math.min(n,row.members.length)},Infinity):0,fullAtmosphere=transportReady;
    function atmosphericContext(lat,lon,timeMs){return nearestTransport(lat,lon,timeMs)||{level:925,rain:0,vertical:0,pbl:null,time:timeMs,fallback:true}}
    function visitKernel(lat,lon,visited,survival){var cy=Math.round((lat+12)/step),cx=Math.round((lon-94)/step);for(var dy=-2;dy<=2;dy++)for(var dx=-2;dx<=2;dx++){var yi=cy+dy,xi=cx+dx,cellLat=yi*step-12,cellLon=xi*step+94,distance=distanceKm([lat,lon],[cellLat,cellLon]);if(distance>75)continue;var weight=Math.exp(-.5*Math.pow(distance/kernelKm,2))*survival,key=yi+'|'+xi;visited[key]=Math.max(visited[key]||0,weight)}}
    function visitSegment(from,to,visited,survival){var segments=Math.max(1,Math.ceil(distanceKm(from,to)/15));for(var i=0;i<=segments;i++){var fraction=i/segments;visitKernel(from[0]+(to[0]-from[0])*fraction,from[1]+(to[1]-from[1])*fraction,visited,survival)}}
    complexes.forEach(function(source){var sourceVotes={};for(var memberIndex=0;memberIndex<memberCount;memberIndex++){var memberVisited={},lat=source.lat,lon=source.lon,origin=[lat,lon],trackTime=Math.max(source.time,end-86400000),survival=1;visitKernel(lat,lon,memberVisited,survival);for(var hour=0;hour<24&&trackTime<=end;hour++){var weather=atmosphericContext(lat,lon,trackTime),member=nearestEnsembleMember(lat,lon,trackTime,memberIndex,weather.level);if(!member)break;var next=destination(lat,lon,(member.direction+180)%360,member.speed);survival*=transportSurvivalStep(weather);if(survival<.15)break;visitSegment([lat,lon],next,memberVisited,survival);lat=next[0];lon=next[1];trackTime+=3600000;maxTravel=Math.max(maxTravel,distanceKm(origin,[lat,lon]))}Object.keys(memberVisited).forEach(function(key){sourceVotes[key]=(sourceVotes[key]||0)+memberVisited[key]})}Object.keys(sourceVotes).forEach(function(key){var support=Math.round(sourceVotes[key]/memberCount*source.reliability*100);cells[key]=Math.max(cells[key]||0,support)})});
    complexes.forEach(function(source){var lat=source.lat,lon=source.lon,origin=[lat,lon],path=[[lat,lon]],trackTime=Math.max(source.time,end-86400000),survival=1;for(var hour=0;hour<24&&trackTime<=end;hour++){var wind=nearestTransport(lat,lon,trackTime),weather=wind||atmosphericContext(lat,lon,trackTime),reference=wind||nearestEnsembleMember(lat,lon,trackTime,0,925);if(!reference)break;var next=destination(lat,lon,(reference.direction+180)%360,reference.speed);survival*=transportSurvivalStep(weather);if(survival<.15)break;lat=next[0];lon=next[1];path.push([lat,lon]);trackTime+=3600000;maxTravel=Math.max(maxTravel,distanceKm(origin,[lat,lon]))}if(path.length>1)traces.push({path:path,source:source})});
    return {cells:cells,step:step,kernelKm:kernelKm,maxTravel:maxTravel,maxProbability:Math.max.apply(null,Object.keys(cells).map(function(key){return cells[key]})),complexCount:complexes.length,excludedComplexCount:allComplexes.length-complexes.length-screenedOut.length,screenedOutCount:screenedOut.length,screenedOut:screenedOut,complexes:complexes,traces:traces,ensemble:ensembleReady,memberCount:memberCount,fullAtmosphere:fullAtmosphere};
  }
  function smokeContours(field){
    if(!window.turf)throw Error('Turf unavailable');
    var keys=Object.keys(field.cells);if(!keys.length)return [];
    var parsed=keys.map(function(key){return key.split('|').map(Number)}),ys=parsed.map(function(p){return p[0]}),xs=parsed.map(function(p){return p[1]}),minY=Math.min.apply(null,ys)-2,maxY=Math.max.apply(null,ys)+2,minX=Math.min.apply(null,xs)-2,maxX=Math.max.apply(null,xs)+2,points=[];
    for(var yi=minY;yi<=maxY;yi++)for(var xi=minX;xi<=maxX;xi++){var lat=yi*field.step-12,lon=xi*field.step+94,score=field.cells[yi+'|'+xi]||0;points.push(turf.point([lon,lat],{score:score}))}
    var thresholds=[1,26,51,76],result=[],surface=turf.featureCollection(points);
    thresholds.forEach(function(threshold){var bands=turf.isobands(surface,[threshold-.01,101],{zProperty:'score'});(bands.features||[]).forEach(function(feature){turf.flattenEach(feature,function(part){if(!part.geometry||turf.area(part)<=1000000)return;var smoothed=turf.polygonSmooth(part,{iterations:1});(smoothed.features||[]).forEach(function(shape){if(turf.area(shape)>1000000)result.push({feature:shape,score:threshold,range:[threshold,100]})})})})});
    return result;
  }
  function renderSmoke(){
    groups.smoke.clearLayers();
    lastSmokeField=null;
    var summary=document.getElementById('smoke-summary'),en=smokeEnglish();
    updateSmokeProductLabel();
    if(period===30){summary.className='fw-smoke-summary';summary.innerHTML=en?'<strong>30-day hotspot history</strong><p>GEFS transport corridors are disabled. This period is used only for historical hotspot markers and statistics.</p>':'<strong>Riwayat hotspot 30 hari</strong><p>Koridor transport GEFS dinonaktifkan. Periode ini hanya untuk marker dan statistik historis hotspot.</p>';return}
    if(period===7){if(!hotspotGeo||!window.turf){summary.className='fw-smoke-summary';summary.innerHTML=en?'<strong>Repeated fire sources · 7 days</strong><p>Source data are incomplete.</p>':'<strong>Sumber api berulang · 7 hari</strong><p>Data sumber belum lengkap.</p>';return}renderRepeatedSources(summary,en);return}
    if(!hotspotGeo||!hotspotModelReady||!ensembleReady||!window.turf){
      summary.className='fw-smoke-summary';
      var unavailableReason=!hotspotModelReady?(en?'the FIRMS source snapshot is stale or incomplete':'snapshot sumber FIRMS terlambat atau tidak lengkap'):(!ensembleReady?(ensembleStatus||'data ensemble GEFS belum lengkap'):(en?'the map contour library is unavailable':'pustaka kontur peta tidak tersedia'));
      summary.innerHTML=en?'<strong>GEFS transport corridors unavailable</strong><p>Hotspots remain visible, but trajectory-support corridors are withheld because '+esc(unavailableReason)+'.</p>':'<strong>Koridor transport GEFS belum tersedia</strong><p>Hotspot tetap ditampilkan, tetapi koridor dukungan lintasan tidak dibuat karena '+esc(unavailableReason)+'.</p>';
      return;
    }
    if(observationDate!==currentDate){summary.className='fw-smoke-summary';summary.innerHTML=en?'<strong>GEFS transport corridors</strong><p>The trajectory screening is available only for the current date because historical atmospheric fields are not loaded.</p>':'<strong>Koridor transport GEFS</strong><p>Penyaringan lintasan hanya tersedia untuk tanggal hari ini karena medan atmosfer historis belum dimuat.</p>';return}
    var items=smokeHotspots(),modelHours=24;
    if(!items.length){
      summary.className='fw-smoke-summary';
      summary.innerHTML=en?'<strong>GEFS transport corridors: none</strong><p>No high-confidence hotspot was found in the '+modelHours+'-hour source window. This does not guarantee smoke-free air.</p>':'<strong>Koridor transport GEFS: tidak ada</strong><p>Tidak ada hotspot confidence tinggi dalam jendela sumber '+modelHours+' jam. Ini bukan jaminan udara bebas asap.</p>';
      return;
    }
    var field=smokeField(items),results=smokeContours(field);lastSmokeField=field;
    field.screenedOut.forEach(function(source){var reasons=(source.screening.reasons||[]).join(', '),land=source.landCoverClass==null?'belum tersedia':String(source.landCoverClass),html=en?'<strong>Source withheld</strong><br>'+esc(reasons)+'<br>WorldCover class: '+esc(land)+'<br><small>This thermal anomaly remains visible but does not seed a transport corridor.</small>':'<strong>Sumber ditahan</strong><br>'+esc(reasons)+'<br>Kelas WorldCover: '+esc(land)+'<br><small>Anomali panas tetap terlihat tetapi tidak membentuk koridor transport.</small>';L.circleMarker([source.lat,source.lon],{pane:'hotspotPane',radius:5,color:'#fff',weight:1,fillColor:'#64748b',fillOpacity:.78}).bindTooltip(en?'Withheld source':'Sumber ditahan').bindPopup(html).addTo(groups.smoke)});    if(!field.complexCount){summary.className='fw-smoke-summary';summary.innerHTML=en?'<strong>GEFS transport corridors: withheld</strong><p>'+field.screenedOutCount+' unclassified thermal-anomaly complex(es) did not pass independent source corroboration. Hotspots remain visible, but no transport corridor is drawn.</p>':'<strong>Koridor transport GEFS: ditahan</strong><p>'+field.screenedOutCount+' kompleks anomali panas tidak terklasifikasi belum melewati konfirmasi sumber independen. Hotspot tetap terlihat, tetapi koridor transport tidak dibuat.</p>';return}
    var liveGuide=document.querySelector('.fw-disclaimer p');if(liveGuide)liveGuide.textContent=field.fullAtmosphere?(en?'Colours show kernel-smoothed GEFS ensemble support multiplied by source-evidence reliability. Winds use 925, 850, or 700 hPa according to PBL and vertical-motion screening rules. This is not observed smoke or PM2.5.':'Warna menunjukkan dukungan ensemble GEFS yang dihaluskan dan dikalikan keandalan bukti sumber. Angin memakai 925, 850, atau 700 hPa sesuai aturan penyaringan PBL dan gerak vertikal. Ini bukan asap teramati atau PM2.5.'):(en?'Limited mode: colours show kernel-smoothed GEFS support at 925 hPa. PBL, vertical motion, rain removal, and deterministic GFS reference are unavailable. This is not observed smoke or PM2.5.':'Mode terbatas: warna menunjukkan dukungan GEFS 925 hPa yang dihaluskan. PBL, gerak vertikal, pengurangan oleh hujan, dan referensi GFS deterministik tidak tersedia. Ini bukan asap teramati atau PM2.5.');
    field.traces.forEach(function(trace){L.polyline(trace.path,{pane:'smokePane',className:'smoke-trace-line',color:'#5f5147',weight:1.25,opacity:.55,dashArray:'5 5',interactive:false}).addTo(groups.smoke)});
    field.complexes.forEach(function(source){var sourceTime=new Date(source.time).toLocaleString(en?'en-GB':'id-ID',{timeZone:'Asia/Jakarta',dateStyle:'medium',timeStyle:'short'}),englishReliability=source.reliabilityLabel==='kuat'?'strong':source.reliabilityLabel==='sedang'?'moderate':'limited',html=en?'<strong>Satellite-detection complex</strong><br>'+source.count+' detections · '+source.passCount+' time pass(es) · '+source.satelliteCount+' satellite(s)<br>Source-evidence reliability: '+englishReliability+' ('+Math.round(source.reliability*100)+'%)<br>Total observed FRP: '+source.frp.toFixed(1)+' MW<br>'+sourceTime+' WIB<br><small>This score does not confirm that a fire remains active. Dashed line is the deterministic GFS reference.</small>':'<strong>Kompleks deteksi satelit</strong><br>'+source.count+' deteksi · '+source.passCount+' lintasan waktu · '+source.satelliteCount+' satelit<br>Keandalan bukti sumber: '+source.reliabilityLabel+' ('+Math.round(source.reliability*100)+'%)<br>Total FRP teramati: '+source.frp.toFixed(1)+' MW<br>'+sourceTime+' WIB<br><small>Skor tidak memastikan api masih aktif. Garis putus-putus adalah referensi GFS deterministik.</small>';L.circleMarker([source.lat,source.lon],{pane:'hotspotPane',className:'smoke-source-marker',radius:8,color:'#fff',weight:2,fillColor:'#7f1d1d',fillOpacity:1}).bindTooltip(en?'Satellite-detection source':'Sumber deteksi satelit').bindPopup(html).addTo(groups.smoke)});
    results.forEach(function(result){var html=en?'<strong>GEFS transport-support contour — '+smokeLabel(result.score)+'</strong><br>Kernel-smoothed support: '+result.range[0]+'–'+result.range[1]+'%<br>Valid members: '+field.memberCount+'<br>Gaussian bandwidth: '+field.kernelKm+' km<br>Source window: '+modelHours+' hours<br>Maximum simulated displacement: '+Math.round(field.maxTravel)+' km<br><hr><small>Each equally weighted member contributes at most one distance-decayed vote per cell. FIRMS FRP and CAMS AOD do not change this support value.</small>':'<strong>Kontur dukungan transport GEFS — '+smokeLabel(result.score)+'</strong><br>Dukungan setelah penghalusan kernel: '+result.range[0]+'–'+result.range[1]+'%<br>Anggota valid: '+field.memberCount+'<br>Bandwidth Gaussian: '+field.kernelKm+' km<br>Jendela sumber: '+modelHours+' jam<br>Perpindahan simulasi maksimum: '+Math.round(field.maxTravel)+' km<br><hr><small>Setiap anggota berbobot sama memberi maksimum satu suara yang meluruh terhadap jarak per sel. FRP FIRMS dan AOD CAMS tidak mengubah nilai dukungan ini.</small>';L.geoJSON(result.feature,{pane:'smokePane',style:{color:smokeColor(result.score),weight:2,fillColor:smokeColor(result.score),fillOpacity:.3}}).bindPopup(html,{maxWidth:330}).addTo(groups.smoke)});
    field.traces.forEach(function(trace){L.polyline(trace.path,{pane:'smokePane',color:'#7f1d1d',weight:2.5,opacity:.95,dashArray:'9 6',interactive:false}).addTo(groups.smoke)});
    if(!results.length){summary.className='fw-smoke-summary';summary.innerHTML=en?'<strong>GEFS transport corridors</strong><p>No connected trajectory-support corridor passed the minimum screening threshold.</p>':'<strong>Koridor transport GEFS</strong><p>Tidak ada koridor dukungan lintasan terkoneksi yang melewati ambang penyaringan minimum.</p>';return}
    var maximum=field.maxProbability,strongSources=field.complexes.filter(function(source){return source.reliability>=.8}).length,moderateSources=field.complexes.filter(function(source){return source.reliability>=.6&&source.reliability<.8}).length;
    summary.className='fw-smoke-summary '+smokeClass(maximum);
    var atmosphereNote=field.fullAtmosphere?(en?'PBL, vertical-motion, and precipitation adjustments applied.':'Penyesuaian PBL, gerak vertikal, dan hujan diterapkan.'):(en?'Limited mode: GEFS 925 hPa only; PBL, vertical-motion, and precipitation adjustments are unavailable, so the contour may overstate persistence.':'Mode terbatas: hanya GEFS 925 hPa; penyesuaian PBL, gerak vertikal, dan hujan tidak tersedia sehingga kontur dapat melebihkan persistensi.'),coverageStartText=new Date(ensembleCoverageStart).toLocaleString(en?'en-GB':'id-ID',{timeZone:'Asia/Jakarta',dateStyle:'medium',timeStyle:'short'}),coverageEndText=new Date(ensembleCoverageEnd).toLocaleString(en?'en-GB':'id-ID',{timeZone:'Asia/Jakarta',dateStyle:'medium',timeStyle:'short'}),provenanceNote=(ensembleProvenance&&ensembleProvenance.validated)?(en?'Validated shared cache':'Cache bersama tervalidasi'):(en?'Legacy browser cache; provenance metadata incomplete':'Cache browser lama; metadata provenance belum lengkap'),sourceName=ensembleProvenance&&ensembleProvenance.source||'Open-Meteo / NOAA GEFS';
    summary.innerHTML=en?'<strong>'+modelHours+'-hour kernel-smoothed transport support: '+smokeLabel(maximum)+' (maximum '+maximum+'%)</strong><p>'+results.length+' connected contours from '+field.complexCount+' satellite-detection complexes ('+strongSources+' strong, '+moderateSources+' moderate), calculated from '+field.memberCount+' equally weighted GEFS members with a '+field.kernelKm+' km bandwidth.</p><p><small>'+atmosphereNote+'</small></p><p><small><strong>Model data:</strong> '+esc(sourceName)+' · '+esc(coverageStartText)+' to '+esc(coverageEndText)+' WIB · '+provenanceNote+'.</small></p>':'<strong>Dukungan transport '+modelHours+' jam setelah penghalusan kernel: '+smokeLabel(maximum)+' (maksimum '+maximum+'%)</strong><p>'+results.length+' kontur terkoneksi dari '+field.complexCount+' kompleks deteksi satelit ('+strongSources+' kuat, '+moderateSources+' sedang), dihitung dari '+field.memberCount+' anggota GEFS berbobot sama dengan bandwidth '+field.kernelKm+' km.</p><p><small>'+atmosphereNote+'</small></p><p><small><strong>Data model:</strong> '+esc(sourceName)+' · '+esc(coverageStartText)+' sampai '+esc(coverageEndText)+' WIB · '+provenanceNote+'.</small></p>';
    var validationState=validationStatus&&validationStatus.status||'uncalibrated',reviewedCases=validationStatus&&validationStatus.reviewedScoreableCaseCount||0,candidateCases=validationStatus&&validationStatus.candidateCaseCount||0,validationText=validationState==='calibrated'?(en?'Calibrated on the declared historical sample':'Terkalibrasi pada sampel historis yang dinyatakan'):validationState==='preliminary-calibration'?(en?'Preliminary calibration':'Kalibrasi awal'):(en?'Not yet calibrated':'Belum dikalibrasi');
    summary.insertAdjacentHTML('beforeend',en?'<p><small><strong>Validation status:</strong> '+validationText+' · '+reviewedCases+' independently reviewed scoreable case(s) from '+candidateCases+' candidate(s). Current parameters remain engineering defaults until the declared thresholds are met.</small></p>':'<p><small><strong>Status validasi:</strong> '+validationText+' · '+reviewedCases+' kasus layak skor yang ditinjau independen dari '+candidateCases+' kandidat. Parameter saat ini tetap nilai rekayasa awal sampai ambang yang dinyatakan terpenuhi.</small></p>');
    if(field.screenedOutCount)summary.insertAdjacentHTML('beforeend',en?'<p><small><strong>Source screening:</strong> '+field.screenedOutCount+' unclassified complex(es) were withheld because they lacked independent corroboration or had weak evidence.</small></p>':'<p><small><strong>Penyaringan sumber:</strong> '+field.screenedOutCount+' kompleks tak terklasifikasi ditahan karena belum memiliki konfirmasi independen atau buktinya lemah.</small></p>');
    if(field.excludedComplexCount)summary.insertAdjacentHTML('beforeend',en?'<p><small><strong>Time coverage:</strong> '+field.excludedComplexCount+' source complex(es) were excluded because GEFS did not cover their detection time.</small></p>':'<p><small><strong>Cakupan waktu:</strong> '+field.excludedComplexCount+' kompleks sumber dikeluarkan karena GEFS tidak mencakup waktu deteksinya.</small></p>');
    summary.insertAdjacentHTML('beforeend','<p id="smoke-source-visibility"></p>');updateSourceVisibility();
  }
  function updateSourceVisibility(){smokeEntryLayers.forEach(function(layer){groups.smoke.removeLayer(layer)});smokeEntryLayers=[];var note=document.getElementById('smoke-source-visibility');if(!note||!lastSmokeField)return;var bounds=map.getBounds(),en=smokeEnglish(),visible=lastSmokeField.complexes.filter(function(source){return bounds.contains([source.lat,source.lon])}).length,entries=0;lastSmokeField.traces.forEach(function(trace){if(bounds.contains([trace.source.lat,trace.source.lon]))return;var entry=trace.path.find(function(point){return bounds.contains(point)});if(!entry)return;var km=Math.round(distanceKm([trace.source.lat,trace.source.lon],entry)),html=en?'<strong>Path enters from an off-screen source</strong><br>Source approximately '+km+' km from this entry point.':'<strong>Lintasan masuk dari sumber di luar layar</strong><br>Sumber sekitar '+km+' km dari titik masuk ini.';var marker=L.circleMarker(entry,{pane:'hotspotPane',radius:7,color:'#fff',weight:2,fillColor:'#6d28d9',fillOpacity:1}).bindTooltip(en?'Off-screen source →':'Sumber di luar layar →',{permanent:true,direction:'right',className:'smoke-entry-label'}).bindPopup(html).addTo(groups.smoke);smokeEntryLayers.push(marker);entries++});note.textContent=visible?(en?visible+' fire-complex source(s) are inside the current map view.':visible+' sumber kompleks kebakaran berada di dalam tampilan peta.'):(en?'No source is inside this view. '+entries+' incoming path(s) from off-screen sources are marked in purple.':'Tidak ada sumber di tampilan ini. '+entries+' lintasan masuk dari sumber luar layar ditandai ungu.')}
  function loadAerosol(){
    var grid=[];
    for(var lat=-10;lat<=5;lat+=3)for(var lon=96;lon<=140;lon+=4)grid.push([lat,lon]);
    var lats=grid.map(function(p){return p[0]}).join(','),lons=grid.map(function(p){return p[1]}).join(',');
    var url='https://air-quality-api.open-meteo.com/v1/air-quality?latitude='+lats+'&longitude='+lons+'&current=aerosol_optical_depth,pm2_5&domains=cams_global&timezone=Asia%2FJakarta';
    return fetch(url).then(function(r){if(!r.ok)throw Error('aerosol');return r.json()}).then(function(data){
      var rows=Array.isArray(data)?data:[data];
      aerosolReadings=rows.map(function(row,i){var c=row.current||{},point=grid[i]||grid[0];return {lat:Number(row.latitude)||point[0],lon:Number(row.longitude)||point[1],aod:Math.max(0,Number(c.aerosol_optical_depth)||0),pm25:Math.max(0,Number(c.pm2_5)||0),time:c.time||''}});
      aerosolReady=aerosolReadings.length>0;
      aerosolTime=aerosolReadings[0]&&aerosolReadings[0].time||'';
    }).catch(function(){aerosolReady=false;aerosolReadings=[]})
  }
  function loadTransportWeather(){
    var grid=[];
    for(var lat=-10;lat<=6;lat+=2)for(var lon=96;lon<=140;lon+=2)grid.push([lat,lon]);
    return fetch('data/gfs-atmosphere.json?v='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('cache atmosfer GFS merespons HTTP '+r.status);return r.json()}).then(function(payload){
      var rows=Array.isArray(payload.data)?payload.data:[],target=periodEnd().getTime();
      transportReadings=rows.map(function(row,i){var h=row.hourly||{},point=grid[i]||grid[0];return {lat:Number(row.latitude)||point[0],lon:Number(row.longitude)||point[1],times:(h.time||[]).map(function(t){return new Date(t+'+07:00').getTime()}),levels:{925:{speeds:h.wind_speed_925hPa||[],directions:h.wind_direction_925hPa||[]},850:{speeds:h.wind_speed_850hPa||[],directions:h.wind_direction_850hPa||[]},700:{speeds:h.wind_speed_700hPa||[],directions:h.wind_direction_700hPa||[]}},vertical:h.vertical_velocity_925hPa||[],pbl:h.boundary_layer_height||[],rain:h.precipitation||[]}});
      transportCoverageStart=Date.parse(payload.validFrom)||0;transportCoverageEnd=Date.parse(payload.validUntil)||0;
      transportReady=transportReadings.length===grid.length&&target>=transportCoverageStart&&target<=transportCoverageEnd+3600000;
      if(!transportReady)throw Error('cache atmosfer GFS tidak lengkap atau tidak mencakup waktu model');
      transportProvenance={source:payload.underlyingModel||payload.source||'NOAA/NCEP GFS',generatedAt:payload.generatedAt||null,validated:Boolean(payload.schemaVersion===1&&payload.variables&&payload.variables.indexOf('boundary_layer_height')>=0&&payload.variables.indexOf('vertical_velocity_925hPa')>=0&&payload.variables.indexOf('precipitation')>=0)};
      groups.wind.clearLayers();
      var now=periodEnd().getTime();
      weatherSites.forEach(function(site){var wind=nearestTransport(site[1],site[2],now);if(!wind)return;var travel=(wind.direction+180)%360;transportTime=new Date(wind.time).toLocaleString('sv-SE',{timeZone:'Asia/Jakarta'}).replace(' ','T');var icon=L.divIcon({className:'wind-icon',html:'<span style="display:block;transform:rotate('+travel+'deg)">↑</span>',iconSize:[30,30],iconAnchor:[15,15]});L.marker([site[1],site[2]],{icon:icon}).bindPopup('<strong>Angin GFS '+wind.level+' hPa '+esc(site[0])+'</strong><br>Bergerak ke '+Math.round(travel)+'° · '+Math.round(wind.speed)+' km/j<br><small>Lapisan dipilih dari PBL · '+esc(transportTime)+' WIB</small>').addTo(groups.wind)})
    }).catch(function(){transportReady=false;transportReadings=[];transportCoverageStart=0;transportCoverageEnd=0;transportProvenance=null})
  }
  function loadEnsembleWeather(){
    var grid=[];for(var lat=-10;lat<=5;lat+=3)for(var lon=96;lon<=140;lon+=4)grid.push([lat,lon]);
    function accept(data,status){var rows=Array.isArray(data)?data:[data],parsed=rows.map(function(row,i){var h=row.hourly||{},point=grid[i]||grid[0],keys=Object.keys(h),speedKeys=keys.filter(function(k){return /^wind_speed_925hPa(_member\d+)?$/.test(k)}),members=speedKeys.map(function(speedKey){var suffix=speedKey.replace('wind_speed_925hPa',''),levels={};[925,850,700].forEach(function(level){levels[level]={speeds:h['wind_speed_'+level+'hPa'+suffix]||[],directions:h['wind_direction_'+level+'hPa'+suffix]||[]}});return {levels:levels}}).filter(function(m){return m.levels[925].directions.length});return {lat:Number(row.latitude)||point[0],lon:Number(row.longitude)||point[1],times:(h.time||[]).map(function(t){return new Date(t+'+07:00').getTime()}).filter(isFinite),members:members}}).filter(function(row){return row.members.length&&row.times.length}),target=periodEnd().getTime(),start=parsed.length?Math.max.apply(null,parsed.map(function(row){return row.times[0]})):0,end=parsed.length?Math.min.apply(null,parsed.map(function(row){return row.times[row.times.length-1]})):0;if(!parsed.length||target<start||target>end+3600000)return false;ensembleReadings=parsed;ensembleCoverageStart=start;ensembleCoverageEnd=end;ensembleReady=true;ensembleStatus=status||'';ensembleTime=new Date(start).toLocaleDateString('sv-SE',{timeZone:'Asia/Jakarta'});return true}
    var cached=null;try{cached=JSON.parse(localStorage.getItem('yg-gefs-multilevel-cache')||'null')}catch(ignore){}
    return fetch('data/gefs-multilevel.json?v='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('cache GEFS server merespons HTTP '+r.status);return r.json()}).then(function(payload){
      if(!payload.data||!payload.data.length||!accept(payload.data,'cache GEFS server mencakup waktu model'))throw Error('cache GEFS server kosong atau tidak mencakup waktu model');
      ensembleProvenance={validated:Boolean(payload.schemaVersion===2&&payload.source&&payload.validFrom&&payload.validUntil&&Number(payload.memberCount)>=2),source:payload.underlyingModel||payload.source||'Open-Meteo / NOAA GEFS',generatedAt:payload.generatedAt||null};
      try{localStorage.setItem('yg-gefs-multilevel-cache',JSON.stringify({savedAt:Date.now(),data:payload.data,metadata:{schemaVersion:payload.schemaVersion,generatedAt:payload.generatedAt,validFrom:payload.validFrom,validUntil:payload.validUntil,source:payload.source,underlyingModel:payload.underlyingModel,memberCount:payload.memberCount}}))}catch(ignore){}
    }).catch(function(serverError){
      if(cached&&cached.data&&accept(cached.data,'cache GEFS browser mencakup waktu model')){var metadata=cached.metadata||{};ensembleProvenance={validated:Boolean(metadata.schemaVersion===2&&metadata.source&&metadata.validFrom&&metadata.validUntil&&Number(metadata.memberCount)>=2),source:metadata.underlyingModel||metadata.source||'Open-Meteo / NOAA GEFS',generatedAt:metadata.generatedAt||null};return}
      ensembleReady=false;ensembleReadings=[];ensembleCoverageStart=0;ensembleCoverageEnd=0;ensembleProvenance=null;ensembleStatus=serverError.message+'; pembaruan GEFS hanya dijalankan oleh cache server untuk menjaga batas layanan'
    })
  }
  function loadWeather(){
    return fetch('data/weather-riau.json?v='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('weather cache');return r.json()}).then(function(d){
      var observed=new Date(d.validTime),ageHours=(Date.now()-observed.getTime())/3600000,timeText=!isNaN(observed)?observed.toLocaleString('id-ID',{timeZone:'Asia/Jakarta',dateStyle:'short',timeStyle:'short'})+' WIB':'waktu tidak diketahui';
      weatherReadings=[];weatherReady=false;
      document.getElementById('kpi-weather').textContent=Number.isFinite(Number(d.temperatureC))?Math.round(Number(d.temperatureC))+'°C':'—';
      document.getElementById('weather-detail').textContent='Prakiraan MET Norway · '+Math.round(Number(d.windSpeedKmh)||0)+' km/j · '+timeText+(ageHours>12?' · data terlambat':'');
    }).catch(function(){weatherReadings=[];weatherReady=false;document.getElementById('kpi-weather').textContent='Tidak tersedia';document.getElementById('weather-detail').textContent='Cache cuaca belum tersedia'})
  }
  function loadValidationStatus(){return fetch('data/smoke-validation-status.json?v='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('validation status');return r.json()}).then(function(data){validationStatus=data}).catch(function(){validationStatus=null})}
  function toggleRain(on){var status=document.getElementById('rain-status');if(!on){groups.rain.clearLayers();rainLayer=null;if(status)status.textContent='Aktifkan layer untuk melihat citra radar hujan terbaru.';return}var msg=document.getElementById('map-message');msg.hidden=false;msg.textContent='Memuat kondisi hujan saat ini…';if(status)status.textContent='Memuat waktu citra radar terbaru…';fetch('https://api.rainviewer.com/public/weather-maps.json').then(function(r){if(!r.ok)throw Error('rain radar');return r.json()}).then(function(d){var frames=d.radar&&d.radar.past||[],f=frames[frames.length-1];if(!f)throw Error('no frame');groups.rain.clearLayers();rainLayer=L.tileLayer('https://tilecache.rainviewer.com'+f.path+'/256/{z}/{x}/{y}/2/1_1.png',{opacity:.55,maxNativeZoom:7,maxZoom:18,attribution:'RainViewer · citra radar terbaru'}).addTo(groups.rain);var observed=new Date(Number(f.time)*1000),timeText=!isNaN(observed)?observed.toLocaleString('id-ID',{timeZone:'Asia/Jakarta',dateStyle:'medium',timeStyle:'short'})+' WIB':'waktu terbaru tersedia';if(status)status.textContent='Citra radar: '+timeText+'. Menunjukkan kondisi sekitar waktu tersebut, bukan akumulasi hujan.';msg.hidden=true}).catch(function(){if(status)status.textContent='Radar hujan saat ini belum tersedia. Jangan gunakan layer ini untuk menyimpulkan kondisi hujan.';msg.hidden=false;msg.textContent='Radar hujan saat ini sedang tidak tersedia';setTimeout(function(){msg.hidden=true},4000)})}
  function setLayerChecked(id,on){var c=document.querySelector('[data-layer="'+id+'"]');if(c)c.checked=on;if(id==='rain'){toggleRain(on);if(on&&!map.hasLayer(groups.rain))groups.rain.addTo(map);return}if(id==='smoke'&&on)renderSmoke();if(on){if(!map.hasLayer(groups[id]))groups[id].addTo(map)}else if(map.hasLayer(groups[id]))map.removeLayer(groups[id])}
  function selectProduct(id){document.querySelectorAll('[data-product]').forEach(function(b){b.classList.toggle('active',b.dataset.product===id)});if(id==='hotspots'){setLayerChecked('hotspots',true)}if(id==='wind'){setLayerChecked('wind',true)}if(id==='rain'){setLayerChecked('rain',true)}if(id==='smoke'){setLayerChecked('smoke',true);setLayerChecked('hotspots',true);setLayerChecked('wind',true)}}
  function observationLabel(value){
    return new Date(value+'T12:00:00+07:00').toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Jakarta'});
  }
  function updateHotspotFreshness(){
    var generated=hotspotGeo&&hotspotGeo.generatedAt?new Date(hotspotGeo.generatedAt):null;
    var age=generated&&!isNaN(generated)?Math.max(0,Date.now()-generated.getTime()):Infinity;
    var hours=age/3600000;
    hotspotLatestObservation=(hotspotGeo&&hotspotGeo.features||[]).reduce(function(latest,feature){var time=pointTime(feature);return !isNaN(time)&&(!latest||time>latest)?time:latest},null);
    hotspotModelReady=!!hotspotGeo&&hotspotGeo.sourceStatus!=='partial'&&hours<=6;
    if(hotspotGeo&&hotspotGeo.sourceStatus==='partial')hotspotStatusText='Peringatan · data FIRMS parsial';
    else if(hours>6)hotspotStatusText='Peringatan · data FIRMS terlambat';
    else hotspotStatusText='Near real-time · high confidence';
    document.getElementById('data-status').textContent=observationDate===currentDate?hotspotStatusText:'Arsip harian';
    var generatedText=generated&&!isNaN(generated)?generated.toLocaleString('id-ID',{timeZone:'Asia/Jakarta'}):'belum tersedia',observedText=hotspotLatestObservation?hotspotLatestObservation.toLocaleString('id-ID',{timeZone:'Asia/Jakarta'}):'belum tersedia';
    document.getElementById('updated-at').textContent='Snapshot: '+generatedText+' WIB | observasi terakhir: '+observedText+' WIB';
  }
  function updateMapDateBadge(){
    if(!mapDateBadge)return;
    var isToday=observationDate===currentDate;
    mapDateBadge.querySelector('strong').textContent=observationLabel(observationDate);
    mapDateBadge.querySelector('small').textContent=isToday?'Mosaik harian · data hari ini mungkin masih parsial':'Mosaik harian · arsip tanggal terpilih';
  }
  function updateObservationDate(value){
    observationDate=value;satelliteLayer.setParams({time:value});
    var isToday=value===currentDate,label=observationLabel(value);
    document.getElementById('condition-title').textContent='Pengamatan satelit '+label+(isToday?' · sementara':'');
    document.getElementById('condition-copy').textContent=isToday?'Data hari ini diperbarui bertahap mengikuti lintasan satelit; area kosong belum tentu berarti tidak ada asap atau hotspot.':'Arsip pengamatan pada tanggal yang dipilih. Hanya hotspot berkeyakinan tinggi yang dipakai untuk prioritas.';
    document.getElementById('data-status').textContent=isToday?hotspotStatusText:'Arsip harian';
    updateMapDateBadge();
  }
  function addMapBadge(){var badge=L.control({position:'bottomleft'});badge.onAdd=function(){var div=L.DomUtil.create('div','fw-layer-badge');div.innerHTML='<strong>HOTSPOT INTERAKTIF: INDONESIA</strong><span>High confidence · rekap desa khusus wilayah YG</span>';return div};badge.addTo(map)}
  function addMapDateBadge(){var badge=L.control({position:'topright'});badge.onAdd=function(){var div=L.DomUtil.create('div','fw-map-date-badge');div.setAttribute('aria-label','Tanggal citra satelit MODIS');div.innerHTML='<span>CITRA MODIS TERRA</span><strong>—</strong><small>Mosaik harian</small>';mapDateBadge=div;updateMapDateBadge();return div};badge.addTo(map)}
  addMapBadge();
  addMapDateBadge();
  Promise.all([fetch('data/desa_intervensi.geojson').then(function(r){return r.json()}),fetch('data/village-forest-analytics.json').then(function(r){return r.json()}),fetch('data/hotspot-high-confidence.geojson?v='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('hotspot');return r.json()}),fetch('data/indonesia-boundary.geojson').then(function(r){if(!r.ok)throw Error('batas daratan');return r.json()}),pointLayer('data/fdrs.geojson',groups.fdrs,'fdrs','FDRS'),pointLayer('data/sekat_kanal.geojson',groups.canals,'canal','Sekat kanal'),loadWeather(),loadAerosol(),loadTransportWeather(),loadEnsembleWeather(),loadValidationStatus()]).then(function(v){villageGeo=v[0];analytics=v[1];hotspotGeo=v[2];var landFeature=v[3]&&v[3].features&&v[3].features[0],before=(hotspotGeo.features||[]).length;if(landFeature&&landFeature.geometry){hotspotGeo.features=(hotspotGeo.features||[]).filter(function(f){return f.geometry&&pointInGeometry(f.geometry.coordinates,landFeature.geometry)});hotspotGeo.offshoreFiltered=before-hotspotGeo.features.length}document.getElementById('kpi-fdrs').textContent=v[4];document.getElementById('kpi-canals').textContent=v[5];updateHotspotFreshness();refreshHotspots();renderSmoke()}).catch(function(){hotspotStatusText='Data hotspot gagal dimuat';document.getElementById('data-status').textContent=hotspotStatusText;document.getElementById('updated-at').textContent='Periksa koneksi atau pembaruan FIRMS';renderSmoke()});
  document.getElementById('period-control').addEventListener('click',function(e){var b=e.target.closest('button');if(!b)return;period=Number(b.dataset.period);this.querySelectorAll('button').forEach(function(x){x.classList.toggle('active',x===b)});document.getElementById('kpi-period').textContent=b.textContent;refreshHotspots();renderSmoke()});
  document.querySelectorAll('[data-layer]').forEach(function(c){c.addEventListener('change',function(){setLayerChecked(c.dataset.layer,c.checked)})});
  document.querySelectorAll('[data-product]').forEach(function(b){b.addEventListener('click',function(){selectProduct(b.dataset.product)})});
  dateInput.addEventListener('change',function(){if(dateInput.value){if(dateInput.value>currentDate)dateInput.value=currentDate;updateObservationDate(dateInput.value);refreshHotspots();renderSmoke()}});updateObservationDate(observationDate);
  document.getElementById('zoom-id').onclick=function(){map.fitBounds(indonesiaBounds,{padding:[8,8]})};
  document.getElementById('zoom-yg').onclick=function(){if(ygBounds&&ygBounds.isValid())map.fitBounds(ygBounds.pad(.08))};
  window.addEventListener('yg:languagechange',function(){renderSmoke()});
  map.on('moveend',updateSourceVisibility);
  var windLevel=document.getElementById('wind-level');if(windLevel)windLevel.onchange=function(e){var note=document.getElementById('map-message');if(e.target.value==='800'){note.hidden=false;note.textContent='Data angin 2.500 kaki belum tersedia; peta tetap menampilkan angin permukaan agar tidak memberi visual yang keliru.';e.target.value='10';setTimeout(function(){note.hidden=true},5000)}};
})();
