(function(){
  'use strict';
  var API='https://script.google.com/macros/s/AKfycbxeGTDZXkR0DyLZmBHTq2M-52Iu4dTTGpH164S7sYHg8qPzvffobC6-r-TBLVHMT3HU-A/exec?page=public-reports';
  var CALLBACK='ygMonitoringDashboardCallback';
  var records=[],groups=[];
  var list=document.getElementById('monitor-list');
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function parseJSON(v){if(!v)return{};if(typeof v==='object')return v;try{return JSON.parse(v);}catch(e){return{};}}
  function dateValue(v){var d=new Date(v||0);return isNaN(d.getTime())?new Date(0):d;}
  function fmtDate(v){var d=dateValue(v);return d.getTime()?d.toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}):'—';}
  function typeOf(p,m){var id=String(p.targetLayerId||m.monitoringType||'').toLowerCase();if(id==='fdrs'||/water|muka air|fdrs/.test(id))return'Tinggi Muka Air/FDRS';if(/restorasi.*hutan|imbo putuih/.test(id))return'Restorasi Hutan';if(/restorasi.*gambut/.test(id))return'Restorasi Gambut';if(/area_mangrove|penanaman/.test(id))return'Penanaman Mangrove';if(/hutan.*mangrove/.test(id))return'Hutan Mangrove';if(/sekat/.test(id))return'Sekat Kanal';if(/apo/.test(id))return'APO';if(/nursery|pembibitan/.test(id))return'Pembibitan';if(/kopi/.test(id))return'Agroforestri/Kopi';return m.monitoringType||p.targetLayerLabel||'Monitoring Umum';}
  function waterStatus(cm){var n=Number(cm);if(!isFinite(n))return null;if(n>=-20)return{key:'baik',label:'Sangat basah'};if(n>=-40)return{key:'waspada',label:'Perlu dipantau'};return{key:'masalah',label:'Waspada kering'};}
  function statusOf(p,m){var ws=waterStatus(m.waterTableCm);if(ws)return ws;var text=String(m.condition||p.condition||p.description||'').toLowerCase();if(/rusak berat|hilang|kritis|tindak lanjut|mati|kering/.test(text))return{key:'masalah',label:'Perlu tindak lanjut'};if(/sedang|rusak ringan|pantau|waspada/.test(text))return{key:'waspada',label:'Perlu dipantau'};return{key:'baik',label:m.condition||'Baik/normal'};}
  function normalize(feature,index){var p=feature.properties||{};if(String(p.reportType||'').toLowerCase()!=='monitoring')return null;var m=parseJSON(p.proposedInformation);if(!Object.keys(m).length)m=parseJSON(p.proposedChanges).monitoring||{};var title=p.locationName||p.title||'Objek monitoring';var objectId=p.targetObjectId||((p.targetSourceType||'program_layer')+'|'+p.targetLayerId+'|'+title.toLowerCase().trim());return{id:p.monitoringId||p.reportId||index,objectId:objectId,title:title,type:typeOf(p,m),date:p.activityDate||p.receivedAt||p.verifiedAt,location:[p.village,p.district,p.regency].filter(Boolean).join(', '),description:p.description||m.notes||'',photos:Array.isArray(p.photos)?p.photos:[],props:p,metrics:m,status:statusOf(p,m)};}
  function groupData(items){var map={};items.forEach(function(r){(map[r.objectId]||(map[r.objectId]=[])).push(r);});return Object.keys(map).map(function(k){var history=map[k].sort(function(a,b){return dateValue(b.date)-dateValue(a.date);});return{key:k,latest:history[0],history:history};});}
  function metricItems(r){var m=r.metrics||{},out=[];if(r.type==='Tinggi Muka Air/FDRS'){out.push(['Muka air',m.waterTableCm!==undefined&&m.waterTableCm!==''?m.waterTableCm+' cm':'—']);out.push(['Kondisi pelampung',m.floatCondition||m.instrumentCondition||'—']);out.push(['Cuaca',m.weather||'—']);out.push(['Riwayat',r.historyCount+' kali']);}else{if(m.survivalPercent)out.push(['Survival',m.survivalPercent+'%']);if(m.averageHeightCm)out.push(['Tinggi rata-rata',m.averageHeightCm+' cm']);if(m.averageDiameterCm)out.push(['Diameter rata-rata',m.averageDiameterCm+' cm']);if(m.sedimentationCm)out.push(['Sedimentasi',m.sedimentationCm+' cm']);if(m.aliveCount)out.push(['Hidup/berfungsi',m.aliveCount]);if(m.deadOrDamagedCount)out.push(['Mati/rusak',m.deadOrDamagedCount]);if(m.monitoredAreaHa)out.push(['Luas',m.monitoredAreaHa+' ha']);while(out.length<4)out.push(out.length===0?['Kondisi',r.status.label]:['Riwayat',r.historyCount+' kali']);}return out.slice(0,4);}
  function render(){var q=document.getElementById('monitor-search').value.toLowerCase(),type=document.getElementById('monitor-type').value,status=document.getElementById('monitor-status').value,sort=document.getElementById('monitor-sort').value;var filtered=groups.filter(function(g){var r=g.latest;return(!q||(r.title+' '+r.location+' '+r.type).toLowerCase().indexOf(q)>-1)&&(!type||r.type===type)&&(!status||r.status.key===status);});filtered.sort(function(a,b){if(sort==='name')return a.latest.title.localeCompare(b.latest.title);if(sort==='risk'){var rank={masalah:0,waspada:1,baik:2};return rank[a.latest.status.key]-rank[b.latest.status.key];}return dateValue(b.latest.date)-dateValue(a.latest.date);});document.getElementById('result-count').textContent=filtered.length+' objek';if(!filtered.length){list.innerHTML='<div class="empty">Belum ada hasil monitoring terverifikasi yang sesuai filter.</div>';return;}list.innerHTML=filtered.map(function(g){var r=g.latest;r.historyCount=g.history.length;var metrics=metricItems(r).map(function(x){return'<div class="metric"><span>'+esc(x[0])+'</span><strong>'+esc(x[1])+'</strong></div>';}).join('');return'<article class="monitor-card"><div class="card-top"><div><span class="type-label">'+esc(r.type.toUpperCase())+'</span><h3>'+esc(r.title)+'</h3><span class="location">'+esc(r.location||'Lokasi belum dicantumkan')+'</span></div><span class="status '+r.status.key+'">'+esc(r.status.label)+'</span></div><div class="metric-grid">'+metrics+'</div><div class="card-actions"><small>Terakhir '+esc(fmtDate(r.date))+' · '+g.history.length+' riwayat</small><button class="link" data-detail="'+esc(g.key)+'" type="button">Lihat riwayat →</button></div></article>';}).join('');}
  function stats(){document.getElementById('stat-total').textContent=records.length;document.getElementById('stat-objects').textContent=groups.length;var action=groups.filter(function(g){return g.latest.status.key==='masalah';});document.getElementById('stat-action').textContent=action.length;document.getElementById('stat-latest').textContent=records.length?fmtDate(records.slice().sort(function(a,b){return dateValue(b.date)-dateValue(a.date);})[0].date):'—';document.getElementById('action-list').innerHTML=action.length?action.slice(0,6).map(function(g){return'<div class="action-item"><strong>'+esc(g.latest.title)+'</strong><span>'+esc(g.latest.status.label)+' · '+esc(fmtDate(g.latest.date))+'</span></div>';}).join(''):'<p>Belum ada objek berstatus tindak lanjut.</p>';}
  function filters(){var types=Array.from(new Set(records.map(function(r){return r.type;}))).sort();document.getElementById('monitor-type').innerHTML='<option value="">Semua jenis</option>'+types.map(function(t){return'<option>'+esc(t)+'</option>';}).join('');document.getElementById('category-strip').innerHTML='<button class="category-chip active" data-type="">Semua</button>'+types.map(function(t){var n=groups.filter(function(g){return g.latest.type===t;}).length;return'<button class="category-chip" data-type="'+esc(t)+'">'+esc(t)+' ('+n+')</button>';}).join('');}
  function openDetail(key){var g=groups.find(function(x){return x.key===key;});if(!g)return;var latest=g.latest;var photos=[];g.history.forEach(function(r){(r.photos||[]).forEach(function(p){if(photos.indexOf(p)<0)photos.push(p);});});var history=g.history.map(function(r){var m=r.metrics||{};var detail;if(r.type==='Tinggi Muka Air/FDRS'&&m.waterTableCm!==undefined){detail='<b>Muka air: '+esc(m.waterTableCm)+' cm</b> · '+esc(m.floatCondition||'kondisi pelampung tidak dicatat');}else{var parts=[];if(m.survivalPercent)parts.push('Survival '+esc(m.survivalPercent)+'%');if(m.averageHeightCm)parts.push('Tinggi '+esc(m.averageHeightCm)+' cm');if(m.averageDiameterCm)parts.push('Diameter '+esc(m.averageDiameterCm)+' cm');if(m.sedimentationCm)parts.push('Sedimentasi '+esc(m.sedimentationCm)+' cm');detail=(parts.length?'<b>'+parts.join(' · ')+'</b><br>':'')+esc(r.description||m.notes||'Tidak ada catatan.');}return'<div class="history-item"><strong>'+esc(fmtDate(r.date))+'</strong><p>'+detail+'</p></div>';}).join('');document.getElementById('detail-content').innerHTML='<span class="type-label">'+esc(latest.type.toUpperCase())+'</span><h2 id="detail-title">'+esc(latest.title)+'</h2><p class="location">'+esc(latest.location)+'</p><h3>Riwayat monitoring</h3><div class="history">'+history+'</div>'+(photos.length?'<h3>Dokumentasi</h3><div class="photo-grid">'+photos.map(function(u){return'<a href="'+esc(u)+'" target="_blank" rel="noopener"><img src="'+esc(u)+'" alt="Dokumentasi monitoring" loading="lazy"></a>';}).join('')+'</div>':'');var modal=document.getElementById('detail-modal');modal.classList.add('open');modal.setAttribute('aria-hidden','false');}
  window[CALLBACK]=function(data){var features=data&&Array.isArray(data.features)?data.features:[];records=features.map(normalize).filter(Boolean);groups=groupData(records);stats();filters();render();};
  ['monitor-search','monitor-type','monitor-status','monitor-sort'].forEach(function(id){document.getElementById(id).addEventListener(id==='monitor-search'?'input':'change',render);});document.addEventListener('click',function(e){var d=e.target.closest('[data-detail]');if(d)openDetail(d.getAttribute('data-detail'));var chip=e.target.closest('.category-chip');if(chip){document.querySelectorAll('.category-chip').forEach(function(c){c.classList.remove('active');});chip.classList.add('active');document.getElementById('monitor-type').value=chip.getAttribute('data-type');render();}if(e.target.closest('[data-close-modal]')){var m=document.getElementById('detail-modal');m.classList.remove('open');m.setAttribute('aria-hidden','true');}});document.addEventListener('keydown',function(e){if(e.key==='Escape')document.querySelector('[data-close-modal]').click();});
  var script=document.createElement('script');script.src=API+'&callback='+CALLBACK+'&t='+Date.now();script.async=true;script.onerror=function(){list.innerHTML='<div class="empty">Data monitoring belum dapat dimuat. Periksa koneksi atau endpoint Apps Script.</div>';};document.head.appendChild(script);
})();
