const ALLOWED_ORIGINS = new Set(['https://webgisyg.id','https://www.webgisyg.id']);
function cors(request){
  const origin=request.headers.get('origin')||'';
  return {
    'access-control-allow-origin': ALLOWED_ORIGINS.has(origin)?origin:'https://webgisyg.id',
    'access-control-allow-methods':'GET, HEAD, POST, PUT, OPTIONS',
    'access-control-allow-headers':'authorization, content-type, x-file-name',
    'access-control-max-age':'3600',
    vary:'Origin',
    'x-content-type-options':'nosniff'
  };
}
function reply(request,value,status=200,extra={}){return new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...cors(request),...extra}})}
function normalizeJson(value){let current=value;for(let i=0;i<2&&typeof current==='string';i++){try{current=JSON.parse(current)}catch{return null}}return current&&typeof current==='object'?current:null}
async function validStaffToken(request,env){const token=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'').trim()||'';if(!token)return false;const upstream=new URL(env.APPS_SCRIPT_BASE);upstream.searchParams.set('page','staff-reports');upstream.searchParams.set('sessionToken',token);try{const response=await fetch(upstream.toString(),{headers:{accept:'application/json','user-agent':'YG-GeoPortal-Drone-API/1.0'},redirect:'follow'});if(!response.ok)return false;const data=normalizeJson(await response.json());return Boolean(data)&&data.requiresLogin!==true&&data.ok!==false}catch{return false}}
function safeName(value){return String(value||'photo.jpg').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,140)||'photo.jpg'}
async function readJson(env,key,fallback=null){const object=await env.PUBLIC_SNAPSHOTS?.get(key);if(!object)return fallback;try{return JSON.parse(await object.text())}catch{return fallback}}
async function writeJson(env,key,value){await env.PUBLIC_SNAPSHOTS.put(key,JSON.stringify(value),{httpMetadata:{contentType:'application/json; charset=utf-8',cacheControl:'no-store'}})}
function jobKey(id){return `drone/jobs/${id}.json`}
async function queueJob(env,id){const key='drone/queue/pending.json';const queue=await readJson(env,key,{jobs:[]});const jobs=Array.isArray(queue?.jobs)?queue.jobs.map(String):[];if(!jobs.includes(id))jobs.push(id);await writeJson(env,key,{jobs,updatedAt:new Date().toISOString()})}
function newJob(body={}){const id=`drn-${crypto.randomUUID()}`;return{id,title:String(body.title||body.area||'Survei drone').slice(0,160),project:String(body.project||'YG GeoPortal').slice(0,160),sourceType:body.sourceType==='drive'?'drive':'upload',driveUrl:body.sourceType==='drive'?String(body.driveUrl||'').trim():null,status:body.sourceType==='drive'?'pending':'uploading',files:[],createdAt:new Date().toISOString(),accessToken:crypto.randomUUID().replace(/-/g,'')}}
async function createJob(request,env){const body=await request.json().catch(()=>({}));const job=newJob(body);if(job.sourceType==='drive'&&!/^https:\/\/drive\.google\.com\/drive\/folders\/[a-zA-Z0-9_-]+/i.test(job.driveUrl||''))return reply(request,{ok:false,error:'invalid_drive_folder_url'},400);await writeJson(env,jobKey(job.id),job);if(job.status==='pending')await queueJob(env,job.id);return reply(request,{ok:true,job})}
async function getJob(request,env,id){const job=await readJson(env,jobKey(id));return job?reply(request,{ok:true,job}):reply(request,{ok:false,error:'job_not_found'},404)}
async function uploadFile(request,env,id,encodedName){const job=await readJson(env,jobKey(id));if(!job)return reply(request,{ok:false,error:'job_not_found'},404);if(job.sourceType!=='upload'||!['uploading','pending'].includes(job.status))return reply(request,{ok:false,error:'job_not_uploadable'},409);const name=safeName(decodeURIComponent(encodedName||'photo.jpg'));const type=request.headers.get('content-type')||'application/octet-stream';if(!/^image\/(jpeg|jpg)$/i.test(type)&&!/\.jpe?g$/i.test(name))return reply(request,{ok:false,error:'jpeg_only'},415);const size=Number(request.headers.get('content-length')||0);if(size&&size>95*1024*1024)return reply(request,{ok:false,error:'file_too_large'},413);const key=`drone/uploads/${id}/${name}`;await env.PUBLIC_SNAPSHOTS.put(key,request.body,{httpMetadata:{contentType:type,cacheControl:'private, max-age=0'}});const files=Array.isArray(job.files)?job.files.filter(f=>f?.key!==key):[];files.push({name,key,bytes:size||null});job.files=files;job.updatedAt=new Date().toISOString();await writeJson(env,jobKey(id),job);return reply(request,{ok:true,id,file:{name,key},uploaded:files.length})}
async function finalizeUpload(request,env,id){const job=await readJson(env,jobKey(id));if(!job)return reply(request,{ok:false,error:'job_not_found'},404);if(job.sourceType!=='upload')return reply(request,{ok:false,error:'not_upload_job'},409);if(!Array.isArray(job.files)||job.files.length<3)return reply(request,{ok:false,error:'minimum_three_photos'},400);job.status='pending';job.queuedAt=new Date().toISOString();await writeJson(env,jobKey(id),job);await queueJob(env,id);return reply(request,{ok:true,job})}
async function serveCog(request,env,id,url){const job=await readJson(env,jobKey(id));if(!job||job.status!=='ready'||!job.cogKey)return reply(request,{ok:false,error:'orthomosaic_not_ready'},404);const access=String(url.searchParams.get('access')||'');if(!access||access!==job.accessToken)return reply(request,{ok:false,error:'unauthorized'},401);const rangeHeader=request.headers.get('range');const object=await env.PUBLIC_SNAPSHOTS.get(job.cogKey,rangeHeader?{range:request.headers}:undefined);if(!object)return reply(request,{ok:false,error:'cog_missing'},404);const headers=new Headers(cors(request));object.writeHttpMetadata(headers);headers.set('etag',object.httpEtag);headers.set('accept-ranges','bytes');headers.set('cache-control','private, max-age=3600');if(object.range){const offset=object.range.offset||0;const length=object.range.length||object.size;headers.set('content-range',`bytes ${offset}-${offset+length-1}/${object.size}`)}return new Response(request.method==='HEAD'?null:object.body,{status:object.range?206:200,headers})}
export function isDroneRoute(pathname){return pathname==='/api/drone/jobs'||pathname.startsWith('/api/drone/jobs/')}
export async function handleDroneRequest(request,env,url){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors(request)});const cogMatch=url.pathname.match(/^\/api\/drone\/jobs\/(drn-[a-zA-Z0-9-]+)\/cog$/);if(cogMatch&&(request.method==='GET'||request.method==='HEAD'))return serveCog(request,env,cogMatch[1],url);if(!await validStaffToken(request,env))return reply(request,{ok:false,error:'unauthorized'},401);if(url.pathname==='/api/drone/jobs'&&request.method==='POST')return createJob(request,env);const fileMatch=url.pathname.match(/^\/api\/drone\/jobs\/(drn-[a-zA-Z0-9-]+)\/files\/(.+)$/);if(fileMatch&&request.method==='PUT')return uploadFile(request,env,fileMatch[1],fileMatch[2]);const finalMatch=url.pathname.match(/^\/api\/drone\/jobs\/(drn-[a-zA-Z0-9-]+)\/finalize$/);if(finalMatch&&request.method==='POST')return finalizeUpload(request,env,finalMatch[1]);const jobMatch=url.pathname.match(/^\/api\/drone\/jobs\/(drn-[a-zA-Z0-9-]+)$/);if(jobMatch&&request.method==='GET')return getJob(request,env,jobMatch[1]);return reply(request,{ok:false,error:'not_found'},404)}
